name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make build
      run: mkdir build
    - name: cmake
      run: cmake .. ./build
    - name: make 
      run: make ./build
    - name: make check 
      run: make check ./build
    - name: make distcheck
      run: make distcheck ./build
